export const zzVari = [{'ExchCode': 'C', 'VariCode': 'CF', 'VariName': '棉花'},
                {'ExchCode': 'C', 'VariCode': 'FG', 'VariName': '玻璃'},
                {'ExchCode': 'C', 'VariCode': 'JR', 'VariName': '粳稻'},
                {'ExchCode': 'C', 'VariCode': 'LR', 'VariName': '晚籼'},
                {'ExchCode': 'C', 'VariCode': 'MA', 'VariName': '甲醇'},
                {'ExchCode': 'C', 'VariCode': 'OI', 'VariName': '菜油'},
                {'ExchCode': 'C', 'VariCode': 'PM', 'VariName': '普麦'},
                {'ExchCode': 'C', 'VariCode': 'RI', 'VariName': '早籼'},
                {'ExchCode': 'C', 'VariCode': 'RM', 'VariName': '菜粕'},
                {'ExchCode': 'C', 'VariCode': 'RS', 'VariName': '菜籽'},
                {'ExchCode': 'C', 'VariCode': 'SF', 'VariName': '硅铁'},
                {'ExchCode': 'C', 'VariCode': 'SM', 'VariName': '锰硅'},
                {'ExchCode': 'C', 'VariCode': 'SR', 'VariName': '白糖'},
                {'ExchCode': 'C', 'VariCode': 'TA', 'VariName': 'PTA'},
                {'ExchCode': 'C', 'VariCode': 'WH', 'VariName': '强麦'},
                {'ExchCode': 'C', 'VariCode': 'ZC', 'VariName': '动力煤'},
                {'ExchCode': 'C', 'VariCode': 'CY', 'VariName': '棉纱'}]

export const dlVari = [{'ExchCode': 'B', 'VariCode': 'a', 'VariName': '豆一'},
                {'ExchCode': 'B', 'VariCode': 'b', 'VariName': '豆二'},
                {'ExchCode': 'B', 'VariCode': 'm', 'VariName': '豆粕'},
                {'ExchCode': 'B', 'VariCode': 'y', 'VariName': '豆油'},
                {'ExchCode': 'B', 'VariCode': 'p', 'VariName': '棕榈油'},
                {'ExchCode': 'B', 'VariCode': 'c', 'VariName': '玉米'},
                {'ExchCode': 'B', 'VariCode': 'cs', 'VariName': '玉米淀粉'},
                {'ExchCode': 'B', 'VariCode': 'jd', 'VariName': '鸡蛋'},
                {'ExchCode': 'B', 'VariCode': 'fb', 'VariName': '纤维板'},
                {'ExchCode': 'B', 'VariCode': 'bb', 'VariName': '胶合板'},
                {'ExchCode': 'B', 'VariCode': 'l', 'VariName': '聚乙烯'},
                {'ExchCode': 'B', 'VariCode': 'v', 'VariName': '聚氯乙烯'},
                {'ExchCode': 'B', 'VariCode': 'pp', 'VariName': '聚丙烯'},
                {'ExchCode': 'B', 'VariCode': 'j', 'VariName': '焦炭'},
                {'ExchCode': 'B', 'VariCode': 'jm', 'VariName': '焦煤'},
                {'ExchCode': 'B', 'VariCode': 'i', 'VariName': '铁矿石'}]

export const shVari = [{'ExchCode': 'A', 'VariCode': 'cu', 'VariName': '铜'},
                {'ExchCode': 'A', 'VariCode': 'al', 'VariName': '铝'},
                {'ExchCode': 'A', 'VariCode': 'zn', 'VariName': '锌'},
                {'ExchCode': 'A', 'VariCode': 'pb', 'VariName': '铅'},
                {'ExchCode': 'A', 'VariCode': 'sn', 'VariName': '锡'},
                {'ExchCode': 'A', 'VariCode': 'ni', 'VariName': '镍'},
                {'ExchCode': 'A', 'VariCode': 'au', 'VariName': '黄金'},
                {'ExchCode': 'A', 'VariCode': 'ag', 'VariName': '白银'},
                {'ExchCode': 'A', 'VariCode': 'rb', 'VariName': '螺纹钢'},
                {'ExchCode': 'A', 'VariCode': 'wr', 'VariName': '线材'},
                {'ExchCode': 'A', 'VariCode': 'hc', 'VariName': '热轧卷板'},
                {'ExchCode': 'A', 'VariCode': 'fu', 'VariName': '燃料油'},
                {'ExchCode': 'A', 'VariCode': 'bu', 'VariName': '沥青'},
                {'ExchCode': 'A', 'VariCode': 'ru', 'VariName': '天然橡胶'}]
export const deliv1 = '2017-05'
export const deliv2 = '2017-09'
export const deliv3 = '2018-01'
